apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2
spec:
  serviceSelector:
    matchLabels:
      cilium-lb-pool: default-pool
  externalIPs: true
  loadBalancerIPs: true
