apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2
spec:
  serviceSelector:
    matchLabels:
      cilium-lb-pool: default-pool
  interfaces:
    - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true
