apiVersion: apps/v1
kind: Deployment
metadata:
  name: gramnuri-web
spec:
  selector:
    matchLabels:
      app: gramnuri-web
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-image-pull-secrets
      containers:
        - name: gramnuri-web
          envFrom:
            - secretRef:
                name: gramnuri-client-secrets
