apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
patches:
  - path: rollout-patch.yaml
    target:
      kind: Rollout
      name: gramnuri-web
  - path: httproute-patch.yaml
    target:
      kind: HTTPRoute
      name: gramnuri-web-httproute
images:
  - name: ghcr.io/igh9410/gramnuri-web
    newTag: "944aa5963ff60a551127d8ae8ce2fb5f64a2ddf8"
