apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
patches:
  - path: rollout-patch.yaml
    target:
      kind: Rollout
      name: gramnuri-web
  - path: httproute-patch.yaml
    target:
      kind: HTTPRoute
      name: gramnuri-web-httproute
images:
  - name: ghcr.io/igh9410/gramnuri-web
    newTag: "bc6d2931c1d22a645c4f5db064e532743bd42071"
