apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: gramnuri-web
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: gramnuri-web
          image: ghcr.io/igh9410/gramnuri-web
          envFrom:
            - secretRef:
                name: gramnuri-client-secrets
