cluster:
  name: default
hubble:
  relay:
    enabled: true
  ui:
    enabled: false
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 192.168.0.0/16
l2announcements:
  enabled: true
operator:
  replicas: 1
routingMode: tunnel
tunnelProtocol: vxlan
kubeProxyReplacement: true
# Required for bootstrap when kubeProxyReplacement=true
# Allows Cilium to connect directly to API server instead of service IP
k8sServiceHost: 192.168.45.199
k8sServicePort: 6443
ingressController:
  enabled: true
  loadbalancerMode: shared
  default: true
