cluster:
  name: default
hubble:
  relay:
    enabled: true
  ui:
    enabled: false
ingressController:
  default: true
  enabled: true
  loadbalancerMode: shared
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 192.168.0.0/16
k8sServiceHost: 192.168.45.199
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
operator:
  replicas: 1
routingMode: native
socketLB.hostNamespaceOnly: true
tunnelProtocol: vxlan
