# Custom values for kube-prometheus-stack
# This file contains only the customizations we want to apply

# Global settings
global:
  rbac:
    create: true
    createAggregateClusterRoles: false

# Prometheus configuration
prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: "30d"
    retentionSize: "8GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    # Allow discovery of ServiceMonitors in all namespaces
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      runAsNonRoot: false
    containerSecurityContext:
      privileged: true
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
      allowPrivilegeEscalation: true
    additionalPrometheusRules:
      - name: custom-rules-http5xx
        groups:
          - name: http-errors
            rules:
              - alert: Http5xxError
                expr: increase(http_requests_total{job="dev-gramnuri-api", code=~"5.."}[1m]) > 0
                for: 0m
                labels:
                  severity: critical
                  namespace: dev
                annotations:
                  summary: "HTTP 5xx error on dev-gramnuri-api"
                  description: "Service {{ $labels.job }} in namespace {{ $labels.namespace }} is returning 5xx errors."
  initContainers:
    - name: chown-data
      image: busybox
      command: ["chown", "-R", "0:0", "/prometheus"]
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - name: prometheus-kube-prometheus-stack-prometheus-db
          mountPath: /prometheus

# Alertmanager configuration
alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'null'
      routes:
        - receiver: 'discord-webhook'
          matchers:
            - alertname = "Http5xxError"
          continue: false
    receivers:
      - name: 'null'
      - name: 'discord-webhook'
        webhook_configs:
          - url_secret:
              name: dev-alarms-webhook-url
              key: webhook_url
            send_resolved: true

# Grafana configuration
grafana:
  enabled: true
  defaultDashboardsTimezone: "UTC"
  serviceMonitor:
    enabled: true
  ingress:
    enabled: true
    ingressClassName: "cilium"
    hosts:
      - grafana.geonhyukim.com
    tls: false
  persistence:
    enabled: true
    storageClassName: local-path
    size: 1Gi
  # Disable init container that's causing permission issues
  initChownData:
    enabled: false
  # Set proper security context for Grafana
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true
      searchNamespace: ALL

# Node Exporter
nodeExporter:
  enabled: true

# Prometheus Operator
prometheusOperator:
  enabled: true
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Kube State Metrics
kubeStateMetrics:
  enabled: true

# Default rules
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubeControllerManager: true
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true
