apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: monitoring
data:
  loki-rules.yaml: |
    groups:
      - name: gramnuri-api-errors
        interval: 1m
        rules:
          # Alert when ERROR logs are detected in gramnuri-api (any environment)
          - alert: GoAPIErrorLogged
            expr: |
              sum by (namespace) (rate({app="gramnuri-api"} |~ "ERROR:" [1m])) > 0
            for: 0m
            labels:
              severity: warning
              app: gramnuri-api
            annotations:
              summary: "Application error detected in gramnuri-api"
              description: "ERROR logs detected in {{ $labels.namespace }}/gramnuri-api. Check logs for details."
          
          # Alert for critical errors (5xx related)
          - alert: GoAPICriticalError
            expr: |
              sum by (namespace) (rate({app="gramnuri-api"} |~ "ERROR:.*5[0-9]{2}" [1m])) > 0
            for: 0m
            labels:
              severity: critical
              app: gramnuri-api
            annotations:
              summary: "Critical 5xx error logged in gramnuri-api"
              description: "5xx related ERROR detected in {{ $labels.namespace }}/gramnuri-api logs."
          
          # Alert for panic/fatal errors
          - alert: GoAPIPanicDetected
            expr: |
              sum by (namespace) (rate({app="gramnuri-api"} |~ "(?i)(panic|fatal)" [1m])) > 0
            for: 0m
            labels:
              severity: critical
              app: gramnuri-api
            annotations:
              summary: "Panic or fatal error in gramnuri-api"
              description: "Application panic or fatal error detected in {{ $labels.namespace }}/gramnuri-api."
