apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: monitoring
data:
  loki-rules.yaml: |
    groups:
      - name: gramnuri-api-errors
        interval: 1m
        rules:
          # Alert when ERROR level logs are detected in gramnuri-api (any environment)
          # Parses JSON logs and extracts the msg field for context
          - alert: GoAPIErrorLogged
            expr: |
              sum by (namespace, msg) (
                rate({app="gramnuri-api"} 
                  | json 
                  | level="error" 
                  | __error__="" [1m])
              ) > 0
            for: 0m
            labels:
              severity: warning
              app: gramnuri-api
            annotations:
              summary: "Application error detected in gramnuri-api"
              description: "Error in {{ $labels.namespace }}/gramnuri-api: {{ $labels.msg }}"
          
          # Alert for critical errors (5xx related in msg or caller)
          - alert: GoAPICriticalError
            expr: |
              sum by (namespace, msg) (
                rate({app="gramnuri-api"} 
                  | json 
                  | level="error" 
                  | msg=~".*5[0-9]{2}.*" 
                  | __error__="" [1m])
              ) > 0
            for: 0m
            labels:
              severity: critical
              app: gramnuri-api
            annotations:
              summary: "Critical 5xx error logged in gramnuri-api"
              description: "5xx error in {{ $labels.namespace }}/gramnuri-api: {{ $labels.msg }}"
          
          # Alert for panic/fatal errors
          - alert: GoAPIPanicDetected
            expr: |
              sum by (namespace, msg) (
                rate({app="gramnuri-api"} 
                  | json 
                  | level=~"panic|fatal|dpanic" 
                  | __error__="" [1m])
              ) > 0
            for: 0m
            labels:
              severity: critical
              app: gramnuri-api
            annotations:
              summary: "Panic or fatal error in gramnuri-api"
              description: "Critical error in {{ $labels.namespace }}/gramnuri-api: {{ $labels.msg }}"
