apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-rules
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/igh9410/igh9410-infra.git
    targetRevision: main
    path: monitoring/loki
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  revisionHistoryLimit: 10
