apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://openebs.github.io/openebs
      chart: openebs
      targetRevision: "4.3.3"
      helm:
        releaseName: openebs
        valueFiles:
          - $values/argocd/values/openebs.yaml
    - repoURL: https://github.com/igh9410/igh9410-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 10
