apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-webhook-config
  namespace: monitoring
spec:
  route:
    receiver: dev-discord-webhook
    groupBy: ["alertname", "namespace"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    matchers:
      - name: alertname
        value: GramnuriAPIHttp5xxErrorRateWarning|GramnuriAPIHighLatencyP99Warning|GoAPIErrorLogged|GoAPICriticalError|GoAPIPanicDetected
        matchType: "=~"
    routes:
      - receiver: prod-discord-webhook
        matchers:
          - name: alertname
            value: GramnuriAPIHttp5xxErrorRateWarning|GramnuriAPIHighLatencyP99Warning
            matchType: "=~"
          - name: namespace
            value: prod
            matchType: "="
          - name: app
            value: gramnuri-api
            matchType: "="
  receivers:
    - name: dev-discord-webhook
      discordConfigs:
        - apiURL:
            name: dev-alarms-webhook-url
            key: webhook_url
          sendResolved: true
          title: '{{ template "discord.default.title" . }}'
          content: '{{ template "discord.default.message" . }}'
    - name: prod-discord-webhook
      discordConfigs:
        - apiURL:
            name: prod-alarms-webhook-url
            key: webhook_url
          sendResolved: true
          title: '{{ template "discord.default.title" . }}'
          content: '{{ template "discord.default.message" . }}'
