apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: gramnuri-api
  - path: httproute-patch.yaml
    target:
      kind: HTTPRoute
      name: gramnuri-api-httproute
images:
  - name: ghcr.io/igh9410/gramnuri-api
    newTag: d5822a63c3b204809adb4eee4749a5536ebb664d
