kustomize:
  images:
  - asia-northeast3-docker.pkg.dev/gramnuri-dev/gramnuri-repo/gramnuri-api=asia-northeast3-docker.pkg.dev/gramnuri-dev/gramnuri-repo/gramnuri-api:3500eddbe73e7c954325685c4dd3b863d11af7c9
