apiVersion: apps/v1
kind: Deployment
metadata:
  name: gramnuri-api
spec:
  selector:
    matchLabels:
      app: gramnuri-api
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: gramnuri-api
        envFrom:
        - secretRef:
            name: gramnuri-secrets
