apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: dev
resources:
- ../../base
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: gramnuri-api
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: gramnuri-api-ingress
images:
- name: ghcr.io/igh9410/gramnuri-api

#  newName: ghcr.io/igh9410/gramnuri-api
#  newTag: 0d55e3052fc5b2e73db7755c8a92d0e2be36b891
