apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: gramnuri
resources:
- ../../base
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: gramnuri-api
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: gramnuri-api-ingress
images:
- name: icn.vultrcr.com/gramnuri/gramnuri-api
  newTag: 4fd85c45882be8420ed3e6dfc4a2d938f77a7179
