apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: default
resources:
- ../../base
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: gramnuri-api
images:
- name: icn.vultrcr.com/gramnuri/gramnuri-api
  newTag: 0.0.1
