apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: default
resources:
- ../../base
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: gramnuri-api
images:
- name: icn.vultrcr.com/gramnuri/gramnuri-api
  newTag: 4fd85c45882be8420ed3e6dfc4a2d938f77a7179

# Add the new ingress patch here
patchesStrategicMerge:
- ingress-patch.yaml
