---
- name: Set up SSH key authentication and disable password login
  hosts: ubuntu_servers
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: "0700"

    - name: Copy public key to authorized_keys
      ansible.builtin.copy:
        src: ../files/id_rsa_ansible.pub
        dest: ~/.ssh/authorized_keys
        owner: igh9410
        group: igh9410
        mode: "0600"

    - name: Disable password authentication in SSH
      become_user: root
      become: true
      become_method: sudo
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
