apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://cloudnative-pg.github.io/charts
    chart: cluster
    targetRevision: "0.3.1"
    helm:
      releaseName: cloudnative-pg-cluster
      valueFiles:
      - $values/argocd/values/cloudnative-pg-cluster.yaml
  - repoURL: https://github.com/igh9410/igh9410-infra.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  revisionHistoryLimit: 10

  # Ignore secrets that are managed outside of Git
  ignoreDifferences:
  # Ignore the database user credentials (created by the operator)
  - group: ""
    kind: Secret
    name: cnpg-cluster-user-credentials
    jsonPointers:
    - /data
  # Ignore the backup credentials (created by you)
  - group: ""
    kind: Secret
    name: cnpg-cluster-backup-credentials
    jsonPointers:
    - /data
