apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod
resources:
- ../../base
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: artskorner-api
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: artskorner-api-ingress
images:
- name: ghcr.io/igh9410/artskorner-api
