apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: gramnuri-web
  - path: httproute-patch.yaml
    target:
      kind: HTTPRoute
      name: gramnuri-web-httproute
images:
  - name: ghcr.io/igh9410/gramnuri-web
    newTag: "1f6d0931b18af8c3f6259eb1a680a99c95348bf5"
