cluster:
  name: default
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: false
ingressController:
  default: true
  enabled: true
  loadbalancerMode: shared
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16 # default k3s CIDR block
k8sServiceHost: 192.168.45.199
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
operator:
  replicas: 1
routingMode: native
tunnelProtocol: vxlan
socketLB.hostNamespaceOnly: true
ipv4NativeRoutingCIDR: 10.42.0.0/16
autoDirectNodeRoutes: true
directRoutingSkipUnreachable: true
