apiVersion: apps/v1
kind: Deployment
metadata:
  name: gramnuri-api
  labels:
    app: gramnuri-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gramnuri-api
  template:
    metadata:
      labels:
        app: gramnuri-api
    spec:
      containers:
        - name: gramnuri-api
          image: ghcr.io/igh9410/gramnuri-api
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: ghcr-image-pull-secrets
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
