apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-database-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/igh9410/igh9410-infra.git
    targetRevision: HEAD
    path: argocd/secrets
  destination:
    server: https://kubernetes.default.svc
    # The namespace here is a default, but the SealedSecret itself defines
    # its target namespace, so this doesn't affect where the final secret lands.
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  revisionHistoryLimit: 10
