apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-artskorner-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: artskorner-api=ghcr.io/igh9410/artskorner-api
    argocd-image-updater.argoproj.io/artskorner-api.update-strategy: latest
    argocd-image-updater.argoproj.io/artskorner-api.allow-tags: regexp:^.*$
    argocd-image-updater.argoproj.io/artskorner-api.kustomize.image-name: ghcr.io/igh9410/artskorner-api
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-access
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/ghcr.io.creds: secret:argocd/ghcr-creds
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/igh9410/igh9410-infra.git
    targetRevision: main
    path: artskorner/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
