apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gramnuri-api-ingress
spec:
  rules:
    - host: dev-api.gramnuri.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gramnuri-api
                port:
                  number: 80
