apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: gramnuri-api
  - path: httproute-patch.yaml
    target:
      kind: HTTPRoute
      name: gramnuri-api-httproute
images:
  - name: ghcr.io/igh9410/gramnuri-api
    newTag: 0e48ba284ae5bb2ab061b4104f9b5972b55783e2
