apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: gramnuri-api
  - path: httproute-patch.yaml
    target:
      kind: HTTPRoute
      name: gramnuri-api-httproute
images:
  - name: ghcr.io/igh9410/gramnuri-api
    newTag: 39d3bb36a9b25d33d515441e2ccc922b41c5187c
