apiVersion: apps/v1
kind: Deployment
metadata:
  name: artskorner-api
spec:
  selector:
    matchLabels:
      app: artskorner-api
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-creds
      containers:
      - name: artskorner-api
        envFrom:
        - secretRef:
            name: artskorner-secrets
