USER-SUPPLIED VALUES:
applicationSet:
  enabled: false
configs:
  cm:
    dex.config: |
      connectors: []
    url: https://argocd.geonhyukim.com
  params:
    server.admin.enabled: "true"
    server.insecure: "true"
  rbac:
    policy.csv: |
      # Grant geonhyuk user admin privileges
      g, geonhyuk, role:admin

      # Define additional policies if needed
      p, role:admin, applications, *, *, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, projects, *, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, accounts, *, *, allow
      p, role:admin, certificates, *, *, allow
      p, role:admin, gpgkeys, *, *, allow
      p, role:admin, logs, *, *, allow
      p, role:admin, exec, *, *, allow
      p, role:admin, applicationsets, *, *, allow
      p, role:admin, extensions, *, *, allow
    policy.default: role:readonly
global:
  domain: argocd.geonhyukim.com
notifications:
  enabled: false
repoServer:
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
server:
  config:
    url: https://argocd.geonhyukim.com
  extraArgs:
  - --insecure
  ingress:
    annotations:
      testDescription: Terraform attempted to set this annotation for ArgoCD ingress
    enabled: true
    hosts:
    - argocd.geonhyukim.com
    pathType: Prefix
    paths:
    - /
  insecure: true
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  service:
    type: ClusterIP
